// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hytdospixxjsncjrtzva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dGRvc3BpeHhqc25janJ0enZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDI4MTEsImV4cCI6MjA1ODA3ODgxMX0.NX-uYwexK3ZnbCRqZhv5or5N5QMp4OJeBcTLiGxJe14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);